name: CI/CD for React App

# Arbetsflödet körs när en push eller pull request görs till main-branchen
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Använd den Node.js-version som ditt projekt kräver

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --watchAll=false # Kör tester

      - name: Build the React app
        run: npm run dev # Bygger projektet

      # Om du vill distribuera till GitHub Pages
      - name: Deploy to GitHub Pages
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
